/// A `Name` language.
///
/// Consists of Language + Region pairs.
///
/// <https://learn.microsoft.com/en-us/typography/opentype/spec/name#windows-language-ids>
pub const Language = enum(u8) {
    Unknown = 0,
    Afrikaans_SouthAfrica,
    Albanian_Albania,
    Alsatian_France,
    Amharic_Ethiopia,
    Arabic_Algeria,
    Arabic_Bahrain,
    Arabic_Egypt,
    Arabic_Iraq,
    Arabic_Jordan,
    Arabic_Kuwait,
    Arabic_Lebanon,
    Arabic_Libya,
    Arabic_Morocco,
    Arabic_Oman,
    Arabic_Qatar,
    Arabic_SaudiArabia,
    Arabic_Syria,
    Arabic_Tunisia,
    Arabic_UAE,
    Arabic_Yemen,
    Armenian_Armenia,
    Assamese_India,
    Azeri_Cyrillic_Azerbaijan,
    Azeri_Latin_Azerbaijan,
    Bashkir_Russia,
    Basque_Basque,
    Belarusian_Belarus,
    Bengali_Bangladesh,
    Bengali_India,
    Bosnian_Cyrillic_BosniaAndHerzegovina,
    Bosnian_Latin_BosniaAndHerzegovina,
    Breton_France,
    Bulgarian_Bulgaria,
    Catalan_Catalan,
    Chinese_HongKongSAR,
    Chinese_MacaoSAR,
    Chinese_PeoplesRepublicOfChina,
    Chinese_Singapore,
    Chinese_Taiwan,
    Corsican_France,
    Croatian_Croatia,
    Croatian_Latin_BosniaAndHerzegovina,
    Czech_CzechRepublic,
    Danish_Denmark,
    Dari_Afghanistan,
    Divehi_Maldives,
    Dutch_Belgium,
    Dutch_Netherlands,
    English_Australia,
    English_Belize,
    English_Canada,
    English_Caribbean,
    English_India,
    English_Ireland,
    English_Jamaica,
    English_Malaysia,
    English_NewZealand,
    English_RepublicOfThePhilippines,
    English_Singapore,
    English_SouthAfrica,
    English_TrinidadAndTobago,
    English_UnitedKingdom,
    English_UnitedStates,
    English_Zimbabwe,
    Estonian_Estonia,
    Faroese_FaroeIslands,
    Filipino_Philippines,
    Finnish_Finland,
    French_Belgium,
    French_Canada,
    French_France,
    French_Luxembourg,
    French_PrincipalityOfMonaco,
    French_Switzerland,
    Frisian_Netherlands,
    Galician_Galician,
    Georgian_Georgia,
    German_Austria,
    German_Germany,
    German_Liechtenstein,
    German_Luxembourg,
    German_Switzerland,
    Greek_Greece,
    Greenlandic_Greenland,
    Gujarati_India,
    Hausa_Latin_Nigeria,
    Hebrew_Israel,
    Hindi_India,
    Hungarian_Hungary,
    Icelandic_Iceland,
    Igbo_Nigeria,
    Indonesian_Indonesia,
    Inuktitut_Canada,
    Inuktitut_Latin_Canada,
    Irish_Ireland,
    isiXhosa_SouthAfrica,
    isiZulu_SouthAfrica,
    Italian_Italy,
    Italian_Switzerland,
    Japanese_Japan,
    Kannada_India,
    Kazakh_Kazakhstan,
    Khmer_Cambodia,
    Kiche_Guatemala,
    Kinyarwanda_Rwanda,
    Kiswahili_Kenya,
    Konkani_India,
    Korean_Korea,
    Kyrgyz_Kyrgyzstan,
    Lao_LaoPDR,
    Latvian_Latvia,
    Lithuanian_Lithuania,
    LowerSorbian_Germany,
    Luxembourgish_Luxembourg,
    Macedonian_NorthMacedonia,
    Malay_BruneiDarussalam,
    Malay_Malaysia,
    Malayalam_India,
    Maltese_Malta,
    Maori_NewZealand,
    Mapudungun_Chile,
    Marathi_India,
    Mohawk_Mohawk,
    Mongolian_Cyrillic_Mongolia,
    Mongolian_Traditional_PeoplesRepublicOfChina,
    Nepali_Nepal,
    Norwegian_Bokmal_Norway,
    Norwegian_Nynorsk_Norway,
    Occitan_France,
    Odia_India,
    Pashto_Afghanistan,
    Polish_Poland,
    Portuguese_Brazil,
    Portuguese_Portugal,
    Punjabi_India,
    Quechua_Bolivia,
    Quechua_Ecuador,
    Quechua_Peru,
    Romanian_Romania,
    Romansh_Switzerland,
    Russian_Russia,
    Sami_Inari_Finland,
    Sami_Lule_Norway,
    Sami_Lule_Sweden,
    Sami_Northern_Finland,
    Sami_Northern_Norway,
    Sami_Northern_Sweden,
    Sami_Skolt_Finland,
    Sami_Southern_Norway,
    Sami_Southern_Sweden,
    Sanskrit_India,
    Serbian_Cyrillic_BosniaAndHerzegovina,
    Serbian_Cyrillic_Serbia,
    Serbian_Latin_BosniaAndHerzegovina,
    Serbian_Latin_Serbia,
    SesothoSaLeboa_SouthAfrica,
    Setswana_SouthAfrica,
    Sinhala_SriLanka,
    Slovak_Slovakia,
    Slovenian_Slovenia,
    Spanish_Argentina,
    Spanish_Bolivia,
    Spanish_Chile,
    Spanish_Colombia,
    Spanish_CostaRica,
    Spanish_DominicanRepublic,
    Spanish_Ecuador,
    Spanish_ElSalvador,
    Spanish_Guatemala,
    Spanish_Honduras,
    Spanish_Mexico,
    Spanish_Nicaragua,
    Spanish_Panama,
    Spanish_Paraguay,
    Spanish_Peru,
    Spanish_PuertoRico,
    Spanish_ModernSort_Spain,
    Spanish_TraditionalSort_Spain,
    Spanish_UnitedStates,
    Spanish_Uruguay,
    Spanish_Venezuela,
    Swedish_Finland,
    Swedish_Sweden,
    Syriac_Syria,
    Tajik_Cyrillic_Tajikistan,
    Tamazight_Latin_Algeria,
    Tamil_India,
    Tatar_Russia,
    Telugu_India,
    Thai_Thailand,
    Tibetan_PRC,
    Turkish_Turkey,
    Turkmen_Turkmenistan,
    Uighur_PRC,
    Ukrainian_Ukraine,
    UpperSorbian_Germany,
    Urdu_IslamicRepublicOfPakistan,
    Uzbek_Cyrillic_Uzbekistan,
    Uzbek_Latin_Uzbekistan,
    Vietnamese_Vietnam,
    Welsh_UnitedKingdom,
    Wolof_Senegal,
    Yakut_Russia,
    Yi_PRC,
    Yoruba_Nigeria,

    pub fn windows_language(
        id: u16,
    ) Language {
        for (TABLE) |v| {
            if (v[0] == id) return v[1];
        } else return .Unknown;
    }

    /// Returns the primary language.
    pub fn primary_language(
        self: Language,
    ) []const u8 {
        return TABLE[@intFromEnum(self)][2];
    }

    /// Returns a language region.
    pub fn region(
        self: Language,
    ) []const u8 {
        return TABLE[@intFromEnum(self)][3];
    }
};

pub const TABLE: []const struct { u16, Language, []const u8, []const u8 } = &.{
    .{ 0x0000, .Unknown, "Unknown", "Unknown" },
    .{ 0x0436, .Afrikaans_SouthAfrica, "Afrikaans", "South Africa" },
    .{ 0x041C, .Albanian_Albania, "Albanian", "Albania" },
    .{ 0x0484, .Alsatian_France, "Alsatian", "France" },
    .{ 0x045E, .Amharic_Ethiopia, "Amharic", "Ethiopia" },
    .{ 0x1401, .Arabic_Algeria, "Arabic", "Algeria" },
    .{ 0x3C01, .Arabic_Bahrain, "Arabic", "Bahrain" },
    .{ 0x0C01, .Arabic_Egypt, "Arabic", "Egypt" },
    .{ 0x0801, .Arabic_Iraq, "Arabic", "Iraq" },
    .{ 0x2C01, .Arabic_Jordan, "Arabic", "Jordan" },
    .{ 0x3401, .Arabic_Kuwait, "Arabic", "Kuwait" },
    .{ 0x3001, .Arabic_Lebanon, "Arabic", "Lebanon" },
    .{ 0x1001, .Arabic_Libya, "Arabic", "Libya" },
    .{ 0x1801, .Arabic_Morocco, "Arabic", "Morocco" },
    .{ 0x2001, .Arabic_Oman, "Arabic", "Oman" },
    .{ 0x4001, .Arabic_Qatar, "Arabic", "Qatar" },
    .{ 0x0401, .Arabic_SaudiArabia, "Arabic", "Saudi Arabia" },
    .{ 0x2801, .Arabic_Syria, "Arabic", "Syria" },
    .{ 0x1C01, .Arabic_Tunisia, "Arabic", "Tunisia" },
    .{ 0x3801, .Arabic_UAE, "Arabic", "U.A.E." },
    .{ 0x2401, .Arabic_Yemen, "Arabic", "Yemen" },
    .{ 0x042B, .Armenian_Armenia, "Armenian", "Armenia" },
    .{ 0x044D, .Assamese_India, "Assamese", "India" },
    .{ 0x082C, .Azeri_Cyrillic_Azerbaijan, "Azeri (Cyrillic)", "Azerbaijan" },
    .{ 0x042C, .Azeri_Latin_Azerbaijan, "Azeri (Latin)", "Azerbaijan" },
    .{ 0x046D, .Bashkir_Russia, "Bashkir", "Russia" },
    .{ 0x042D, .Basque_Basque, "Basque", "Basque" },
    .{ 0x0423, .Belarusian_Belarus, "Belarusian", "Belarus" },
    .{ 0x0845, .Bengali_Bangladesh, "Bengali", "Bangladesh" },
    .{ 0x0445, .Bengali_India, "Bengali", "India" },
    .{ 0x201A, .Bosnian_Cyrillic_BosniaAndHerzegovina, "Bosnian (Cyrillic)", "Bosnia and Herzegovina" },
    .{ 0x141A, .Bosnian_Latin_BosniaAndHerzegovina, "Bosnian (Latin)", "Bosnia and Herzegovina" },
    .{ 0x047E, .Breton_France, "Breton", "France" },
    .{ 0x0402, .Bulgarian_Bulgaria, "Bulgarian", "Bulgaria" },
    .{ 0x0403, .Catalan_Catalan, "Catalan", "Catalan" },
    .{ 0x0C04, .Chinese_HongKongSAR, "Chinese", "Hong Kong S.A.R." },
    .{ 0x1404, .Chinese_MacaoSAR, "Chinese", "Macao S.A.R." },
    .{ 0x0804, .Chinese_PeoplesRepublicOfChina, "Chinese", "People's Republic of China" },
    .{ 0x1004, .Chinese_Singapore, "Chinese", "Singapore" },
    .{ 0x0404, .Chinese_Taiwan, "Chinese", "Taiwan" },
    .{ 0x0483, .Corsican_France, "Corsican", "France" },
    .{ 0x041A, .Croatian_Croatia, "Croatian", "Croatia" },
    .{ 0x101A, .Croatian_Latin_BosniaAndHerzegovina, "Croatian (Latin)", "Bosnia and Herzegovina" },
    .{ 0x0405, .Czech_CzechRepublic, "Czech", "Czech Republic" },
    .{ 0x0406, .Danish_Denmark, "Danish", "Denmark" },
    .{ 0x048C, .Dari_Afghanistan, "Dari", "Afghanistan" },
    .{ 0x0465, .Divehi_Maldives, "Divehi", "Maldives" },
    .{ 0x0813, .Dutch_Belgium, "Dutch", "Belgium" },
    .{ 0x0413, .Dutch_Netherlands, "Dutch", "Netherlands" },
    .{ 0x0C09, .English_Australia, "English", "Australia" },
    .{ 0x2809, .English_Belize, "English", "Belize" },
    .{ 0x1009, .English_Canada, "English", "Canada" },
    .{ 0x2409, .English_Caribbean, "English", "Caribbean" },
    .{ 0x4009, .English_India, "English", "India" },
    .{ 0x1809, .English_Ireland, "English", "Ireland" },
    .{ 0x2009, .English_Jamaica, "English", "Jamaica" },
    .{ 0x4409, .English_Malaysia, "English", "Malaysia" },
    .{ 0x1409, .English_NewZealand, "English", "New Zealand" },
    .{ 0x3409, .English_RepublicOfThePhilippines, "English", "Republic of the Philippines" },
    .{ 0x4809, .English_Singapore, "English", "Singapore" },
    .{ 0x1C09, .English_SouthAfrica, "English", "South Africa" },
    .{ 0x2C09, .English_TrinidadAndTobago, "English", "Trinidad and Tobago" },
    .{ 0x0809, .English_UnitedKingdom, "English", "United Kingdom" },
    .{ 0x0409, .English_UnitedStates, "English", "United States" },
    .{ 0x3009, .English_Zimbabwe, "English", "Zimbabwe" },
    .{ 0x0425, .Estonian_Estonia, "Estonian", "Estonia" },
    .{ 0x0438, .Faroese_FaroeIslands, "Faroese", "Faroe Islands" },
    .{ 0x0464, .Filipino_Philippines, "Filipino", "Philippines" },
    .{ 0x040B, .Finnish_Finland, "Finnish", "Finland" },
    .{ 0x080C, .French_Belgium, "French", "Belgium" },
    .{ 0x0C0C, .French_Canada, "French", "Canada" },
    .{ 0x040C, .French_France, "French", "France" },
    .{ 0x140c, .French_Luxembourg, "French", "Luxembourg" },
    .{ 0x180C, .French_PrincipalityOfMonaco, "French", "Principality of Monaco" },
    .{ 0x100C, .French_Switzerland, "French", "Switzerland" },
    .{ 0x0462, .Frisian_Netherlands, "Frisian", "Netherlands" },
    .{ 0x0456, .Galician_Galician, "Galician", "Galician" },
    .{ 0x0437, .Georgian_Georgia, "Georgian", "Georgia" },
    .{ 0x0C07, .German_Austria, "German", "Austria" },
    .{ 0x0407, .German_Germany, "German", "Germany" },
    .{ 0x1407, .German_Liechtenstein, "German", "Liechtenstein" },
    .{ 0x1007, .German_Luxembourg, "German", "Luxembourg" },
    .{ 0x0807, .German_Switzerland, "German", "Switzerland" },
    .{ 0x0408, .Greek_Greece, "Greek", "Greece" },
    .{ 0x046F, .Greenlandic_Greenland, "Greenlandic", "Greenland" },
    .{ 0x0447, .Gujarati_India, "Gujarati", "India" },
    .{ 0x0468, .Hausa_Latin_Nigeria, "Hausa (Latin)", "Nigeria" },
    .{ 0x040D, .Hebrew_Israel, "Hebrew", "Israel" },
    .{ 0x0439, .Hindi_India, "Hindi", "India" },
    .{ 0x040E, .Hungarian_Hungary, "Hungarian", "Hungary" },
    .{ 0x040F, .Icelandic_Iceland, "Icelandic", "Iceland" },
    .{ 0x0470, .Igbo_Nigeria, "Igbo", "Nigeria" },
    .{ 0x0421, .Indonesian_Indonesia, "Indonesian", "Indonesia" },
    .{ 0x045D, .Inuktitut_Canada, "Inuktitut", "Canada" },
    .{ 0x085D, .Inuktitut_Latin_Canada, "Inuktitut (Latin)", "Canada" },
    .{ 0x083C, .Irish_Ireland, "Irish", "Ireland" },
    .{ 0x0434, .isiXhosa_SouthAfrica, "isiXhosa", "South Africa" },
    .{ 0x0435, .isiZulu_SouthAfrica, "isiZulu", "South Africa" },
    .{ 0x0410, .Italian_Italy, "Italian", "Italy" },
    .{ 0x0810, .Italian_Switzerland, "Italian", "Switzerland" },
    .{ 0x0411, .Japanese_Japan, "Japanese", "Japan" },
    .{ 0x044B, .Kannada_India, "Kannada", "India" },
    .{ 0x043F, .Kazakh_Kazakhstan, "Kazakh", "Kazakhstan" },
    .{ 0x0453, .Khmer_Cambodia, "Khmer", "Cambodia" },
    .{ 0x0486, .Kiche_Guatemala, "K'iche", "Guatemala" },
    .{ 0x0487, .Kinyarwanda_Rwanda, "Kinyarwanda", "Rwanda" },
    .{ 0x0441, .Kiswahili_Kenya, "Kiswahili", "Kenya" },
    .{ 0x0457, .Konkani_India, "Konkani", "India" },
    .{ 0x0412, .Korean_Korea, "Korean", "Korea" },
    .{ 0x0440, .Kyrgyz_Kyrgyzstan, "Kyrgyz", "Kyrgyzstan" },
    .{ 0x0454, .Lao_LaoPDR, "Lao", "Lao P.D.R." },
    .{ 0x0426, .Latvian_Latvia, "Latvian", "Latvia" },
    .{ 0x0427, .Lithuanian_Lithuania, "Lithuanian", "Lithuania" },
    .{ 0x082E, .LowerSorbian_Germany, "Lower Sorbian", "Germany" },
    .{ 0x046E, .Luxembourgish_Luxembourg, "Luxembourgish", "Luxembourg" },
    .{ 0x042F, .Macedonian_NorthMacedonia, "Macedonian", "North Macedonia" },
    .{ 0x083E, .Malay_BruneiDarussalam, "Malay", "Brunei Darussalam" },
    .{ 0x043E, .Malay_Malaysia, "Malay", "Malaysia" },
    .{ 0x044C, .Malayalam_India, "Malayalam", "India" },
    .{ 0x043A, .Maltese_Malta, "Maltese", "Malta" },
    .{ 0x0481, .Maori_NewZealand, "Maori", "New Zealand" },
    .{ 0x047A, .Mapudungun_Chile, "Mapudungun", "Chile" },
    .{ 0x044E, .Marathi_India, "Marathi", "India" },
    .{ 0x047C, .Mohawk_Mohawk, "Mohawk", "Mohawk" },
    .{ 0x0450, .Mongolian_Cyrillic_Mongolia, "Mongolian (Cyrillic)", "Mongolia" },
    .{ 0x0850, .Mongolian_Traditional_PeoplesRepublicOfChina, "Mongolian (Traditional)", "People's Republic of China" },
    .{ 0x0461, .Nepali_Nepal, "Nepali", "Nepal" },
    .{ 0x0414, .Norwegian_Bokmal_Norway, "Norwegian (Bokmal)", "Norway" },
    .{ 0x0814, .Norwegian_Nynorsk_Norway, "Norwegian (Nynorsk)", "Norway" },
    .{ 0x0482, .Occitan_France, "Occitan", "France" },
    .{ 0x0448, .Odia_India, "Odia (formerly Oriya)", "India" },
    .{ 0x0463, .Pashto_Afghanistan, "Pashto", "Afghanistan" },
    .{ 0x0415, .Polish_Poland, "Polish", "Poland" },
    .{ 0x0416, .Portuguese_Brazil, "Portuguese", "Brazil" },
    .{ 0x0816, .Portuguese_Portugal, "Portuguese", "Portugal" },
    .{ 0x0446, .Punjabi_India, "Punjabi", "India" },
    .{ 0x046B, .Quechua_Bolivia, "Quechua", "Bolivia" },
    .{ 0x086B, .Quechua_Ecuador, "Quechua", "Ecuador" },
    .{ 0x0C6B, .Quechua_Peru, "Quechua", "Peru" },
    .{ 0x0418, .Romanian_Romania, "Romanian", "Romania" },
    .{ 0x0417, .Romansh_Switzerland, "Romansh", "Switzerland" },
    .{ 0x0419, .Russian_Russia, "Russian", "Russia" },
    .{ 0x243B, .Sami_Inari_Finland, "Sami (Inari)", "Finland" },
    .{ 0x103B, .Sami_Lule_Norway, "Sami (Lule)", "Norway" },
    .{ 0x143B, .Sami_Lule_Sweden, "Sami (Lule)", "Sweden" },
    .{ 0x0C3B, .Sami_Northern_Finland, "Sami (Northern)", "Finland" },
    .{ 0x043B, .Sami_Northern_Norway, "Sami (Northern)", "Norway" },
    .{ 0x083B, .Sami_Northern_Sweden, "Sami (Northern)", "Sweden" },
    .{ 0x203B, .Sami_Skolt_Finland, "Sami (Skolt)", "Finland" },
    .{ 0x183B, .Sami_Southern_Norway, "Sami (Southern)", "Norway" },
    .{ 0x1C3B, .Sami_Southern_Sweden, "Sami (Southern)", "Sweden" },
    .{ 0x044F, .Sanskrit_India, "Sanskrit", "India" },
    .{ 0x1C1A, .Serbian_Cyrillic_BosniaAndHerzegovina, "Serbian (Cyrillic)", "Bosnia and Herzegovina" },
    .{ 0x0C1A, .Serbian_Cyrillic_Serbia, "Serbian (Cyrillic)", "Serbia" },
    .{ 0x181A, .Serbian_Latin_BosniaAndHerzegovina, "Serbian (Latin)", "Bosnia and Herzegovina" },
    .{ 0x081A, .Serbian_Latin_Serbia, "Serbian (Latin)", "Serbia" },
    .{ 0x046C, .SesothoSaLeboa_SouthAfrica, "Sesotho sa Leboa", "South Africa" },
    .{ 0x0432, .Setswana_SouthAfrica, "Setswana", "South Africa" },
    .{ 0x045B, .Sinhala_SriLanka, "Sinhala", "Sri Lanka" },
    .{ 0x041B, .Slovak_Slovakia, "Slovak", "Slovakia" },
    .{ 0x0424, .Slovenian_Slovenia, "Slovenian", "Slovenia" },
    .{ 0x2C0A, .Spanish_Argentina, "Spanish", "Argentina" },
    .{ 0x400A, .Spanish_Bolivia, "Spanish", "Bolivia" },
    .{ 0x340A, .Spanish_Chile, "Spanish", "Chile" },
    .{ 0x240A, .Spanish_Colombia, "Spanish", "Colombia" },
    .{ 0x140A, .Spanish_CostaRica, "Spanish", "Costa Rica" },
    .{ 0x1C0A, .Spanish_DominicanRepublic, "Spanish", "Dominican Republic" },
    .{ 0x300A, .Spanish_Ecuador, "Spanish", "Ecuador" },
    .{ 0x440A, .Spanish_ElSalvador, "Spanish", "El Salvador" },
    .{ 0x100A, .Spanish_Guatemala, "Spanish", "Guatemala" },
    .{ 0x480A, .Spanish_Honduras, "Spanish", "Honduras" },
    .{ 0x080A, .Spanish_Mexico, "Spanish", "Mexico" },
    .{ 0x4C0A, .Spanish_Nicaragua, "Spanish", "Nicaragua" },
    .{ 0x180A, .Spanish_Panama, "Spanish", "Panama" },
    .{ 0x3C0A, .Spanish_Paraguay, "Spanish", "Paraguay" },
    .{ 0x280A, .Spanish_Peru, "Spanish", "Peru" },
    .{ 0x500A, .Spanish_PuertoRico, "Spanish", "Puerto Rico" },
    .{ 0x0C0A, .Spanish_ModernSort_Spain, "Spanish (Modern Sort)", "Spain" },
    .{ 0x040A, .Spanish_TraditionalSort_Spain, "Spanish (Traditional Sort)", "Spain" },
    .{ 0x540A, .Spanish_UnitedStates, "Spanish", "United States" },
    .{ 0x380A, .Spanish_Uruguay, "Spanish", "Uruguay" },
    .{ 0x200A, .Spanish_Venezuela, "Spanish", "Venezuela" },
    .{ 0x081D, .Swedish_Finland, "Swedish", "Finland" },
    .{ 0x041D, .Swedish_Sweden, "Swedish", "Sweden" },
    .{ 0x045A, .Syriac_Syria, "Syriac", "Syria" },
    .{ 0x0428, .Tajik_Cyrillic_Tajikistan, "Tajik (Cyrillic)", "Tajikistan" },
    .{ 0x085F, .Tamazight_Latin_Algeria, "Tamazight (Latin)", "Algeria" },
    .{ 0x0449, .Tamil_India, "Tamil", "India" },
    .{ 0x0444, .Tatar_Russia, "Tatar", "Russia" },
    .{ 0x044A, .Telugu_India, "Telugu", "India" },
    .{ 0x041E, .Thai_Thailand, "Thai", "Thailand" },
    .{ 0x0451, .Tibetan_PRC, "Tibetan", "PRC" },
    .{ 0x041F, .Turkish_Turkey, "Turkish", "Turkey" },
    .{ 0x0442, .Turkmen_Turkmenistan, "Turkmen", "Turkmenistan" },
    .{ 0x0480, .Uighur_PRC, "Uighur", "PRC" },
    .{ 0x0422, .Ukrainian_Ukraine, "Ukrainian", "Ukraine" },
    .{ 0x042E, .UpperSorbian_Germany, "Upper Sorbian", "Germany" },
    .{ 0x0420, .Urdu_IslamicRepublicOfPakistan, "Urdu", "Islamic Republic of Pakistan" },
    .{ 0x0843, .Uzbek_Cyrillic_Uzbekistan, "Uzbek (Cyrillic)", "Uzbekistan" },
    .{ 0x0443, .Uzbek_Latin_Uzbekistan, "Uzbek (Latin)", "Uzbekistan" },
    .{ 0x042A, .Vietnamese_Vietnam, "Vietnamese", "Vietnam" },
    .{ 0x0452, .Welsh_UnitedKingdom, "Welsh", "United Kingdom" },
    .{ 0x0488, .Wolof_Senegal, "Wolof", "Senegal" },
    .{ 0x0485, .Yakut_Russia, "Yakut", "Russia" },
    .{ 0x0478, .Yi_PRC, "Yi", "PRC" },
    .{ 0x046A, .Yoruba_Nigeria, "Yoruba", "Nigeria" },
};
